FINAL_ACADEMIC_WEEK = 38
WEEKS_PER_YEAR = 52
LOOKBACK_YEARS = 3

SARIMA_ORDER = (1, 0, 1)
SARIMA_ORDER_INDIVIDUAL = (1, 1, 1)
SARIMA_SEASONAL_ORDER = (1, 1, 1, WEEKS_PER_YEAR)
SARIMA_SEASONAL_ORDER_ALT = (1, 1, 0, WEEKS_PER_YEAR)
SARIMA_BACHELOR_DEADLINE_WEEKS = (17, 18, 19, 20, 21)
